# Generated by Django 3.2.2 on 2021-07-15 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=150)),
                ('data_admissao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_posto', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('Medicos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Escala_app.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('Folgas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Escala_app.folga')),
                ('Medicos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Escala_app.medico')),
                ('Posto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Escala_app.posto')),
            ],
        ),
    ]
